---
- name: Configure the kernel to keep connections alive when enabling the firewall
  sysctl:
    name: net.netfilter.nf_conntrack_tcp_be_liberal
    value: 1
    state: present
    sysctl_set: yes
    reload: yes
- name: Configuring service
  ufw:
    state: "{{ ufw_state }}"
    logging: "{{ ufw_logging }}"
